language: node_js

node_js:
  - 9
  - 8

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn build

notifications:
  email:
    on_failure: change

after_success:
  - yarn coveralls
